main = ".open-next/worker.js"
name = "blueshift-dashboard"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "learn.blueshift.gg", custom_domain = true }
]

[vars]
NEXT_PUBLIC_APP_URL = "https://learn.blueshift.gg"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
