main = ".open-next/worker.js"
name = "blueshift-dashboard"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

routes = [
    { pattern = "learn.blueshift.gg", custom_domain = true }
]
